# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17f9Fergl6-vTKCrC67LktVbPMf-T42lZ
"""

# =====================================================
# IMPORT LIBRARY
# =====================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# =====================================================
# KONFIGURASI HALAMAN
# =====================================================

st.set_page_config(
    page_title="K-Means Clustering Sekolah",
    page_icon="🏫",
    layout="wide"
)

st.title("🏫 K-Means Clustering Fasilitas Sekolah Dasar")

st.markdown("""
Aplikasi ini digunakan untuk mengelompokkan kecamatan
berdasarkan kondisi fasilitas sekolah menggunakan
algoritma K-Means Clustering.
""")

# =====================================================
# SIDEBAR
# =====================================================

st.sidebar.header("Pengaturan")

k = st.sidebar.slider(
    "Jumlah Cluster",
    min_value=2,
    max_value=10,
    value=3
)

# =====================================================
# UPLOAD DATASET
# =====================================================

uploaded_file = st.file_uploader(
    "Upload Dataset Excel",
    type=["xlsx"]
)

if uploaded_file is not None:

    # =====================================================
    # MEMBACA DATASET
    # =====================================================

    df = pd.read_excel(uploaded_file)

    st.subheader("Dataset Awal")

    st.dataframe(df)

    # =====================================================
    # SIMPAN NAMA KECAMATAN
    # =====================================================

    kecamatan = df["Kecamatan"]

    # =====================================================
    # DATA CLEANING
    # =====================================================

    df_clean = df.drop(columns=[

        'No.',
        'Kecamatan',

        'Ruang UKS Baik',
        'Ruang UKS Rusak',
        'Jumlah Ruang UKS',

        'Laboratorium Baik',
        'Laboratorium Rusak',
        'Jumlah Laboratorium',

        'Kelas Rusak Total',
        'Jumlah Kelas',
        'Ruang Kelas seluruh'

    ], errors="ignore")

    # Missing Value

    df_clean = df_clean.fillna(
        df_clean.median(
            numeric_only=True
        )
    )

    # Hapus kolom konstan

    df_clean = df_clean.loc[
        :,
        df_clean.nunique() > 1
    ]

    st.subheader("Dataset Setelah Cleaning")

    st.dataframe(df_clean)

    # =====================================================
    # STANDARDISASI
    # =====================================================

    scaler = StandardScaler()

    X_scaled = scaler.fit_transform(
        df_clean
    )

    # =====================================================
    # ELBOW METHOD
    # =====================================================

    inertia = []

    for i in range(1,11):

        model = KMeans(
            n_clusters=i,
            random_state=42,
            n_init=10
        )

        model.fit(X_scaled)

        inertia.append(
            model.inertia_
        )

    st.subheader("Elbow Method")

    fig1, ax1 = plt.subplots(
        figsize=(8,5)
    )

    ax1.plot(
        range(1,11),
        inertia,
        marker='o'
    )

    ax1.set_xlabel(
        "Jumlah Cluster"
    )

    ax1.set_ylabel(
        "Inertia"
    )

    ax1.set_title(
        "Elbow Method"
    )

    st.pyplot(fig1)

    # =====================================================
    # K-MEANS
    # =====================================================

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    cluster = kmeans.fit_predict(
        X_scaled
    )

    # =====================================================
    # SILHOUETTE SCORE
    # =====================================================

    score = silhouette_score(
        X_scaled,
        cluster
    )

    st.metric(
        "Silhouette Score",
        round(score,4)
    )

    # =====================================================
    # HASIL CLUSTER
    # =====================================================

    hasil = pd.DataFrame()

    hasil["Kecamatan"] = kecamatan
    hasil["Cluster"] = cluster

    st.subheader(
        "Hasil Clustering"
    )

    st.dataframe(
        hasil
    )

    # =====================================================
    # PCA
    # =====================================================

    pca = PCA(
        n_components=2
    )

    X_pca = pca.fit_transform(
        X_scaled
    )

    centroid_pca = pca.transform(
        kmeans.cluster_centers_
    )

    visualisasi = pd.DataFrame({
        'PCA1': X_pca[:,0],
        'PCA2': X_pca[:,1],
        'Cluster': cluster,
        'Kecamatan': kecamatan
    })

    # =====================================================
    # SCATTER PLOT + CENTROID
    # =====================================================

    st.subheader(
        "Visualisasi Cluster"
    )

    fig2, ax2 = plt.subplots(
        figsize=(12,7)
    )

    sns.scatterplot(
        data=visualisasi,
        x="PCA1",
        y="PCA2",
        hue="Cluster",
        palette="viridis",
        s=120,
        ax=ax2
    )

    for i in range(
        len(visualisasi)
    ):

        ax2.text(
            visualisasi["PCA1"].iloc[i],
            visualisasi["PCA2"].iloc[i],
            visualisasi["Kecamatan"].iloc[i],
            fontsize=8
        )

    ax2.scatter(
        centroid_pca[:,0],
        centroid_pca[:,1],
        c='red',
        marker='X',
        s=400,
        edgecolors='black',
        label='Centroid'
    )

    ax2.set_title(
        "Scatter Plot Cluster + Centroid"
    )

    st.pyplot(fig2)

    # =====================================================
    # DOWNLOAD CSV
    # =====================================================

    csv = hasil.to_csv(
        index=False
    )

    st.download_button(
        "Download Hasil Clustering",
        csv,
        "hasil_clustering.csv",
        "text/csv"
    )